name: CI
on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Create venv and install python packages
        run: |
          python -m pip install --upgrade pip && pip install -r requirements-dev.txt && pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest
      - name: Run Ruff Linter
        run: |
          ruff check .
      - name: Run mypy Type Checking
        run: |
          mypy .
